# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: "https-lenpaul-github-io-lagrange"

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: "UA-143006563-1"

menu:
  - { name: "About Me", path: "menu", url: "about.html" }
  - { name: "Articles", path: "menu", url: "articles.html" }
  - { name: "Logs", path: "menu", url: "logs.html" }
  - { name: "", path: "menu", url: "notes.html" }
  - { name: "", path: "menu", url: "unpublished.html" }

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - { icon: "github", link: "https://www.github.com/larrylawl" }
  - { icon: "linkedin", link: "https://www.linkedin.com/in/larry-law" }
  - { icon: "envelope", link: "mailto:larrylaw97@gmail.com" }
  # - { icon: "rss-square", link: "/feed.xml" }
  - { icon: "rss-square", link: "/rss-feed.xml" }

# Customize site text
pagination:
  next_page: "Newer"
  previous_page: "Older"

sharing_button_prompt: "Feel free to share my articles as well."

related_posts: "You may also enjoy:"

post_date_prefix: "Written on"
